### ISSUE TITLE
css problem with widget and infoItems

### ISSUE THREAD

**Issue by justoverclockl** [flarumite/simple-discussion-views#18]
hi ianm, i've noticed that if i add some items to `DiscussionListItem.infoItems` and after that some widget (that are completely into another position) i get some css view caused (i think) from discussion views (disabled this extension all works fine)

https://i.ibb.co/dPZ1B49/Immagine-2021-09-15-093427.png

can you help me to fix that?

**Comment by imorland** [comment]
Hey @justoverclockl sorry for the long wait!

I **think** this is now solved. Would you mind trying `1.0.4` and letting me know please?

**Comment by justoverclockl** [comment]
![Immagine 2021-11-19 185304](https://user-images.githubusercontent.com/79002016/142668932-33729d5d-27a3-43cc-b40c-b1c9e8adaf2b.png)

now is too much on the left

**Comment by justoverclockl** [comment]
![3163D9B0-E14E-4DBE-9135-2149566B6851](https://user-images.githubusercontent.com/79002016/151430184-34fd92c1-926f-4bd5-b206-2147df7e3c1d.png)

i still have problems on layout

**Comment by imorland** [comment]
This looks like it's an issue with another extension, possibly whatever is adding the additional avatar, or  `Partecipanti` and `Creata il`.
